name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key from secret
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh-key.pem
          chmod 400 ssh-key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@13.126.34.179   <<  'EOF'
            set -e
            cd /var/www/html/laravel

            git pull origin main

            # Fix ownership and permissions before running commands
            sudo chown -R www-data:www-data .
            sudo chmod -R 775 storage bootstrap/cache

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            if [ ! -L public/storage ]; then
              php artisan storage:link
            fi
          EOF

      - name: Clean up SSH key
        run: rm -f ssh-key.pem
